; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:\Users\nhut6\.pio_builds\AquaCare_Stm32

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
monitor_port = COM9
build_flags = 
	-D ENABLE_HWSERIAL3
lib_deps = 
	dfrobot/DFRobot_PH @ ^1.0.0
	adafruit/Adafruit MAX31865 library@^1.6.2
	jan-kra/GravityTDS@^0.0.1
	mandulaj/PZEM-004T-v30@^1.1.2
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
platform_packages = 
	platformio/tool-openocd@~2.1100.0
